-- on commit

CREATE MATERIALIZED VIEW mv_name
BUILD IMMEDIATE
REFRESH FAST ON COMMIT
ENABLE QUERY REWRITE
AS
SELECT * FROM source_table;

CREATE MATERIALIZED VIEW LOG ON source_table;


-- manual

CREATE MATERIALIZED VIEW mv_name
BUILD IMMEDIATE
REFRESH MANUAL
ENABLE QUERY REWRITE
AS
SELECT * FROM source_table;


EXEC DBMS_MVIEW.REFRESH('mv_name');
